### ISSUE TITLE
How can I fetch stream from database (not future)?

### ISSUE THREAD

**Issue by mateoKutnjak** [GeekySingh/flutter_data_caching#1]
I'm using Moor database and to receive updates it returns Stream of data. How can I incorporate Stream to NetworkBoundResource class you provided? 

loadFromDb expects Future data type which don't react to database changes. Thank you

**Comment by GeekySingh** [comment]
Hi, if you look at the definition of NetworkBoundResource function, it returns a Stream of data. If you are using Moor, your query return type should of a stream and it will be handled accordingly.

**Comment by mateoKutnjak** [comment]
Wouldn't ```_safeDatabaseCall``` method in ```BaseRepository``` need return Stream of data with some kind of StreamTransformer? With current implementation no updates on database rows are detected.

**Comment by GeekySingh** [comment]
True. That function was written for a specific purpose. If your requirement is to get a stream of data directly from DB, you can listen to your DB stream directly without making any modifications in the BaseRepository. Otherwise, you can clone the _safeDatabaseCall function and modify it to return Stream, by taking dao function that returns Stream from the DB
